name: PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cs-fixer:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Composer install
        run: composer install

      - name: PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
